import maya.cmds as cmds

cmds.window()
cmds.rowColumnLayout( numberOfColumns=2, columnAlign=(1, 'right'), columnAttach=(2, 'both', 0), columnWidth=(2, 150) )

cmds.text( label='Default' )
cmds.separator()
cmds.text( label='None' )
cmds.separator( style='none' )
cmds.text( label='Single' )
cmds.separator( style='single' )
cmds.text( label='Double' )
cmds.separator( height=10, style='double' )
cmds.text( label='Single Dash' )
cmds.separator( height=10, style='singleDash' )
cmds.text( label='Double Dash' )
cmds.separator( height=40, style='doubleDash' )
cmds.text( label='Etched In' )
cmds.separator( height=40, style='in' )
cmds.text( label='Etched Out' )
cmds.separator( height=40, style='out' )
cmds.setParent( '..' )
cmds.showWindow()